# Generated by Django 4.2.6 on 2023-11-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0003_customuser_bio_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
