# Generated by Django 4.2.7 on 2023-11-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_bookstore", "0002_alter_book_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
