# Generated by Django 4.2.7 on 2023-11-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_bookstore", "0003_alter_book_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="stock",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
