# Generated by Django 4.2.7 on 2023-11-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_bookstore", "0004_alter_book_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="stock",
            field=models.IntegerField(),
        ),
    ]
