# Generated by Django 4.2.6 on 2023-10-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="uncategorized", max_length=255),
        ),
    ]
