# Generated by Django 4.2.6 on 2023-10-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_posts", "0003_post_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(to="app_posts.category"),
        ),
    ]
