# Generated by Django 4.2.6 on 2023-10-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_posts", "0004_category_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
