# Generated by Django 4.2.6 on 2023-10-20 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_posts", "0005_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
    ]
