# Generated by Django 4.2.6 on 2023-10-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_posts", "0007_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
